backend:
  name: git-gateway
  branch: main

media_folder: public/img
public_folder: img

collections:
  - name: "index"
    label: "Home"
    folder: "content/home"
    extension: "md"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "subtitle"
        label: "Subtitle"
        widget: "string"
      - name: "ctaText"
        label: "CTA Text"
        widget: "string"
      - name: "ctaLink"
        label: "CTA Link"
        widget: "string"

      # Challenges Section
      - name: "challengesTitle"
        label: "Challenges Section Title"
        widget: "string"
      - name: "challenges"
        label: "Challenges Section"
        widget: "list"
        fields:
          - label: "Challenge Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Icon"
            name: "icon"
            widget: "image"

      
      # Solutions Section
      - name: "solutionsTitle"
        label: "Solutions Section Title"
        widget: "string"
      - name: "solutions"
        label: "Solutions Section"
        widget: "list"
        fields:
          - label: "Solution Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Points"
            name: "points"
            widget: "list"
            fields:
              - label: "Point"
                name: "point"
                widget: "string"


      # Services Section
      - name: "services"
        label: "Services"
        widget: "list"
        fields:
          - label: "Service Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Button Link"
            name: "buttonLink"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"

      # Expertise Section
      - name: "expertiseTitle"
        label: "Expertise Section Title"
        widget: "string"
      - name: "knowledgeItems"
        label: "Expertise Section (Knowledge Items)"
        widget: "list"
        fields:
          - label: "Item Title"
            name: "title"
            widget: "string"
          - label: "Icon"
            name: "icon"
            widget: "image"

      # Portfolio Section
      - name: "portfolioTitle"
        label: "Portfolio Section Title"
        widget: "string"
      - name: "portfolioItems"
        label: "Portfolio"
        widget: "list"
        fields:
          - label: "Project Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Image"
            name: "image"
            widget: "image"


 
  - name: "navbar"
    label: "Navbar"
    folder: "content"
    file: "navbar.md"
    extension: "md"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "links"
        label: "Links"
        widget: "list"
        fields:
          - name: "name"
            label: "Name"
            widget: "string"
          - name: "href"
            label: "Link"
            widget: "string"
          - name: "dropdown"
            label: "Dropdown"
            widget: "list"
            required: false
            fields:
              - name: "name"
                label: "Name"
                widget: "string"
              - name: "href"
                label: "Link"
                widget: "string"
      - name: "contactButton"
        label: "Kontakt Button"
        widget: "object"
        fields:
          - name: "label"
            label: "Label"
            widget: "string"
          - name: "href"
            label: "Link"
            widget: "string"



  - name: "footer"
    label: "Footer"
    folder: "content"
    file: "footer.md"
    extension: "md"
    slug: "{{slug}}"
    create: true
    fields:
      - name: "logo"
        label: "Logo"
        widget: "image"
      - name: "links"
        label: "Links"
        widget: "object"
        fields:
          - name: "impressum"
            label: "Impressum"
            widget: "string"
          - name: "datenschutz"
            label: "Datenschutz"
            widget: "string"
      - name: "overview"
        label: "Overview"
        widget: "list"
        fields:
          - name: "name"
            label: "Name"
            widget: "string"
          - name: "link"
            label: "Link"
            widget: "string"
      - name: "contact"
        label: "Contact"
        widget: "list"
        fields:
          - name: "type"
            label: "Type"
            widget: "string"
          - name: "label"
            label: "Label"
            widget: "string"
          - name: "link"
            label: "Link"
            widget: "string"
      - name: "socialMedia"
        label: "Social Media"
        widget: "list"
        fields:
          - name: "platform"
            label: "Platform"
            widget: "string"
          - name: "link"
            label: "Link"
            widget: "string"





  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "description"
        label: "Description"
        widget: "text"
      - name: "image"
        label: "Page Image"
        widget: "image"
      - name: "services"
        label: "Services"
        widget: "list"
        fields:
          - label: "Service Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Button Link"
            name: "buttonLink"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
 



 
  - name: "aboutus"
    label: "About Us"
    folder: "content/aboutus"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "description"
        label: "Page Description"
        widget: "text"
      - name: "image"
        label: "Page Image"
        widget: "image"
      - name: "highlight-description"
        label: "Highlight Description"
        widget: "text"
      - name: "highlights"
        label: "Highlights"
        widget: "list"
        fields:
          - name: "image"
            label: "Image"
            widget: "image"
          - name: "image-description"
            label: "Image Description"
            widget: "text"
      - name: "facts"
        label: "Facts and Figures"
        widget: "list"
        fields:
          - name: "icon"
            label: "Icon"
            widget: "select"
            options:
              - city
              - calendar
              - check-circle
          - name: "title"
            label: "Fact Title"
            widget: "string"
          - name: "description"
            label: "Description"
            widget: "string"
      - name: "management"
        label: "Management"
        widget: "list"
        fields:
          - name: "name"
            label: "Name"
            widget: "string"
          - name: "email"
            label: "Email"
            widget: "string"
          - name: "position"
            label: "Position"
            widget: "string"
          - name: "image"
            label: "Image"
            widget: "image"
          - name: "xing"
            label: "Xing Profile"
            widget: "string"
          - name: "linkedin"
            label: "LinkedIn Profile"
            widget: "string"



  - name: "contact"
    label: "Contact"
    folder: "content/contact"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "description"
        label: "Description"
        widget: "text"
      - name: "image"
        label: "Header Image"
        widget: "image"
      - name: "contactForm"
        label: "Contact Form"
        widget: "object"
        fields:
          - name: "formTitle"
            label: "Form Title"
            widget: "string"
          - name: "emailPlaceholder"
            label: "Email Placeholder"
            widget: "string"
          - name: "phonePlaceholder"
            label: "Phone Placeholder" 
            widget: "string"
          - name: "messagePlaceholder"
            label: "Message Placeholder"
            widget: "string"
          - name: "buttonText"
            label: "Button Text"
            widget: "string"
          - name: "senderEmail"
            label: "Sender Email"
            widget: "string"
      - name: "contactInfo"
        label: "Contact Information"
        widget: "object"
        fields:
          - name: "title"
            label: "Section Title"
            widget: "string"
          - name: "infoList"
            label: "Info List"
            widget: "list"
            fields:
              - name: "icon"
                label: "Icon"
                widget: "select"
                options:
                  - phone
                  - envelope
                  - location
              - name: "text"
                label: "Text"
                widget: "string"
          - name: "socialLinks"
            label: "Social Links"
            widget: "list"
            fields:
              - name: "icon"
                label: "Icon"
                widget: "select"
                options:
                  - youtube
                  - linkedin
                  - xing
                  - instagram
              - name: "href"
                label: "URL"
                widget: "string"



  - name: "impressum"
    label: "Impressum"
    folder: "content/impressum"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "description"
        label: "Description"
        widget: "text"
      - name: "image"
        label: "Header Image"
        widget: "image"
      - name: "contactInfo"
        label: "Contact Info"
        widget: "object"
        fields:
          - name: "title"
            label: "Section Title"
            widget: "string"
          - name: "infoList"
            label: "Info List"
            widget: "list"
            fields:
              - name: "icon"
                label: "Icon"
                widget: "select"
                options:
                  - phone
                  - envelope
                  - location
              - name: "text"
                label: "Text"
                widget: "string"
          - name: "socialLinks"
            label: "Social Links"
            widget: "list"
            fields:
              - name: "icon"
                label: "Icon"
                widget: "select"
                options:
                  - youtube
                  - linkedin
                  - xing
                  - instagram
              - name: "href"
                label: "URL"
                widget: "string"
      - name: "impressum"
        label: "Impressum Details"
        widget: "object"
        fields:
          - name: "header"
            label: "Header"
            widget: "string"
          - name: "content"
            label: "Content Blocks"
            widget: "list"
            fields:
              - name: "subheader"
                label: "Subheader"
                widget: "string"
              - name: "text"
                label: "Text"
                widget: "text"
          - name: "registration"
            label: "Registration"
            widget: "object"
            fields:
              - name: "court"
                label: "Court"
                widget: "string"
              - name: "number"
                label: "Number"
                widget: "string"
          - name: "vatId"
            label: "VAT ID"
            widget: "string"


  - name: "dataprivacy"
    label: "Datenschutz"
    folder: "content/dataprivacy"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "description"
        label: "Description"
        widget: "text"
      - name: "image"
        label: "Header Image"
        widget: "image"
      - name: "dataprivacy"
        label: "Datenschutz Abschnitte"
        widget: "list"
        fields:
          - name: "subheader"
            label: "Ãœberschrift"
            widget: "string"
          - name: "text"
            label: "Text"
            widget: "text"
  

  - name: "service"
    label: "Service"
    folder: "content/service"
    slug: "{{slug}}"
    create: true
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "description"
        label: "Description"
        widget: "text"
      - name: "image"
        label: "Header Image"
        widget: "image"
      - name: "services"
        label: "Leistungen"
        widget: "list"
        fields:
          - name: "link"
            label: "Link"
            widget: "string"
          - name: "image"
            label: "Image"
            widget: "image"
          - name: "content"
            label: "Content"
            widget: "list"
            fields:
              - name: "header"
                label: "Title"
                widget: "string"
              - name: "text"
                label: "Text"
                widget: "text"
      - name: "help"
        label: "Hilfe"
        widget: "list"
        fields:
          - name: "header"
            label: "Title"
            widget: "string"
          - name: "text"
            label: "Text"
            widget: "text"
          - name: "button"
            label: "Button"
            widget: "string"
          - name: "management"
            label: "Management"
            widget: "list"
            fields:
              - name: "name"
                label: "Name"
                widget: "string"
              - name: "email"
                label: "Email"
                widget: "string"
              - name: "position"
                label: "Position"
                widget: "string"
              - name: "image"
                label: "Image"
                widget: "image"
      - name: "category"
        label: "Kategorie"
        widget: "list"
        fields:
          - name: "name"
            label: "Name"
            widget: "string"
          - name: "class"
            label: "Klasse"
            widget: "string"
      - name: "tools"
        label: "Tools"
        widget: "list"
        fields:
          - name: "name"
            label: "Name"
            widget: "string"
          - name: "image"
            label: "Image"
            widget: "image"
          - name: "class"
            label: "Klasse"
            widget: "list"
            fields:
              - label: "Class"
                name: "class"
                widget: "string"

